server:
  port: 9010

eureka:
  service-url:
    defaultZone: http://localhost:9010/eureka/
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    preferIpAddress: true
  server:
    wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: discovery-server